name: JoyFlix
package: community.lazycat.app.joyflix
version: 0.1.0
min_os_version: 1.3.8
description: "✨JoyFlix观影平台是一款基于 MoonTV二次开发完全重构的项目 （NEXT.JS） 的影视播放平台，将MoonTV的底层结构代码进行完全的重构及其优化对UI及其交互逻辑进行完全重构"
homepage: https://github.com/jeffernn/joyflix
author: jeffernn
application:
  subdomain: joyflix
  background_task: true

  upstreams:
    - location: /
      backend: http://joyflix-core:3000/
services:
  joyflix-core:
    # ghcr.io/jeffernn/joyflix@sha256:453fd835de93538a880dce307680da0f20d805c575c6ddfe09557f7018a2a877
    image: registry.lazycat.cloud/czyt/jeffernn/joyflix:daa76a620112df14
    ontainer_name: joyflix-core
    environment:
      - USERNAME={{ .U.admin_username }}
      - PASSWORD={{.U.admin_password}}
      - NEXT_PUBLIC_STORAGE_TYPE=redis
      - REDIS_URL=redis://joyflix-redis:6379
    depends_on:
      - joyflix-redis

  joyflix-redis:
    image: registry.lazycat.cloud/edward/library/redis:4c6b9d7b7a334a2e
    binds:
      - /lzcapp/var/redis:/data

locales:
  zh:
    name: "JoyFlix"
    description: "✨JoyFlix观影平台是一款基于 MoonTV二次开发完全重构的项目 （NEXT.JS） 的影视播放平台，将MoonTV的底层结构代码进行完全的重构及其优化对UI及其交互逻辑进行完全重构"
  en:
    name: "JoyFlix"
    description: "MoonTV based on Platform"
